### ISSUE TITLE
作者能否更新一下readme

### ISSUE THREAD

**Issue by zhanghaok** [hgliyuhao/ActiveLearing4NER#1]
作者您好，能否对代码说明一下，low_confidence.json是什么意思呢，是从dev.json挑选出来的吗

**Comment by hgliyuhao** [comment]
low_confidence.json 是通过计算选择出更有标注意义的样本
由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的

这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑

**Comment by zhanghaok** [comment]
> low_confidence.json 是通过计算选择出更有标注意义的样本 由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的
> 
> 这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑

好的，保持关注哈哈😁

**Comment by hgliyuhao** [comment]
> > low_confidence.json 是通过计算选择出更有标注意义的样本 由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的
> > 这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑
> 
> 好的，保持关注哈哈😁

已更新，有疑问随时交流哈

**Comment by zhanghaok** [comment]
> > > low_confidence.json 是通过计算选择出更有标注意义的样本 由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的
> > > 这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑
> > 
> > 
> > 好的，保持关注哈哈😁
> 
> 已更新，有疑问随时交流哈

作者你好，我看了你的源码，请问里面的最小置信度计算是否正确呢？“**最小置信度算法的原理是求出标注模型输出概率积的最大值, 即标注序列的概率积.概率积越小说明不确定度越大, 以此抽样出需要手工标记的样本**”
比如以下面的句子“**我爱中国**”为例：
![image](https://user-images.githubusercontent.com/39120036/198825814-c071525c-a98d-42b7-bfcd-42b30eca3215.png)
在模型的预测结果中，对于我爱中国这句话，最大概率序列的概率值不应该是0.4X0.4X0.6X0.5吗？但是我看作者的源码是分标签计算的

**Comment by hgliyuhao** [comment]
> > > > low_confidence.json 是通过计算选择出更有标注意义的样本 由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的
> > > > 这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑
> > > 
> > > 
> > > 好的，保持关注哈哈😁
> > 
> > 
> > 已更新，有疑问随时交流哈
> 
> 作者你好，我看了你的源码，请问里面的最小置信度计算是否正确呢？“**最小置信度算法的原理是求出标注模型输出概率积的最大值, 即标注序列的概率积.概率积越小说明不确定度越大, 以此抽样出需要手工标记的样本**” 比如以下面的句子“**我爱中国**”为例： ![image](https://user-images.githubusercontent.com/39120036/198825814-c071525c-a98d-42b7-bfcd-42b30eca3215.png) 在模型的预测结果中，对于我爱中国这句话，最大概率序列的概率值不应该是0.4X0.4X0.6X0.5吗？但是我看作者的源码是分标签计算的

如果做非嵌套NER任务时，就是每个位置有且只有一种标签的序列预测任务，最大概率序列的概率值是0.4X0.4X0.6X0.5，这种计算是正确的。
现在很多任务要处理嵌套NER，包括globalPointer的设计也是基于这种考虑。 举一个简单的例子 “西红柿鸡蛋” 西红柿鸡蛋是一道菜的名称 ，西红柿又会是一种蔬菜名称。在“西”字的位置就需要有两个标签。所以这时候计算最大概率就感觉不全面，所以在实现的时候计算了所有标签的概率值。当然这也是直觉上感觉这么做比较合理，在相关论文中并未找到相关的验证，所以在这种嵌套实体，非连续实体的任务上如何进行主动学习更好，期待你的研究，然后分享给我 😁

**Comment by zhanghaok** [comment]
> > > > > low_confidence.json 是通过计算选择出更有标注意义的样本 由于太过久远 我也忘记了low_confidence.json 是否是从dev.json里挑选出来的
> > > > > 这几天我会完善一下这个项目 包括globalpointer的版本 开个小坑
> > > > 
> > > > 
> > > > 好的，保持关注哈哈😁
> > > 
> > > 
> > > 已更新，有疑问随时交流哈
> > 
> > 
> > 作者你好，我看了你的源码，请问里面的最小置信度计算是否正确呢？“**最小置信度算法的原理是求出标注模型输出概率积的最大值, 即标注序列的概率积.概率积越小说明不确定度越大, 以此抽样出需要手工标记的样本**” 比如以下面的句子“**我爱中国**”为例： ![image](https://user-images.githubusercontent.com/39120036/198825814-c071525c-a98d-42b7-bfcd-42b30eca3215.png) 在模型的预测结果中，对于我爱中国这句话，最大概率序列的概率值不应该是0.4X0.4X0.6X0.5吗？但是我看作者的源码是分标签计算的
> 
> 如果做非嵌套NER任务时，就是每个位置有且只有一种标签的序列预测任务，最大概率序列的概率值是0.4X0.4X0.6X0.5，这种计算是正确的。 现在很多任务要处理嵌套NER，包括globalPointer的设计也是基于这种考虑。 举一个简单的例子 “西红柿鸡蛋” 西红柿鸡蛋是一道菜的名称 ，西红柿又会是一种蔬菜名称。在“西”字的位置就需要有两个标签。所以这时候计算最大概率就感觉不全面，所以在实现的时候计算了所有标签的概率值。当然这也是直觉上感觉这么做比较合理，在相关论文中并未找到相关的验证，所以在这种嵌套实体，非连续实体的任务上如何进行主动学习更好，期待你的研究，然后分享给我 😁

好的，感谢作者的解答，我确实没有考虑到嵌套NER，受教了！我i这边暂时在做常规NER的主动学习，后面可能也做嵌套的，如果后面我有好的方案了，分享给你哈哈😁
