### ISSUE TITLE
bert_model.ckpt

### ISSUE THREAD

**Issue by yys-1** [hgliyuhao/ActiveLearing4NER#4]
您好，请问这个文件怎么来的？
 Unsuccessful TensorSliceReader constructor: Failed to find any matching files for pre_models/chinese-roberta-wwm-ext-tf/bert_model.ckpt

**Comment by hgliyuhao** [comment]
这个是哈工大预训练模型 可以去这下载https://github.com/ymcui/Chinese-BERT-wwm
